# Generated by Django 3.2.13 on 2022-06-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biblia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livro', models.CharField(max_length=255)),
                ('capitulo', models.IntegerField()),
                ('versiculo', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Biblia',
                'ordering': ['-id'],
            },
        ),
    ]
